---
version: 2
plan:
  project-key: VW
  key: BROW
  name: brownbag
  description: Created for brownbag
stages:
- Default Stage:
    manual: false
    final: false
    jobs:
    - Default Job
Default Job:
  key: JOB1
  tasks:
  - checkout:
      force-clean-build: false
      description: Checkout Default Repository
  - script:
      interpreter: SHELL
      scripts:
      - ls -la
  artifact-subscriptions: []
repositories:
- brownbagtest:
    scope: global
triggers:
- polling:
    period: '180'
branches:
  create: manually
  delete: never
  link-to-jira: true
notifications: []
labels: []
dependencies:
  require-all-stages-passing: false
  enabled-for-branches: true
  block-strategy: none
  plans: []
other:
  concurrent-build-plugin: system-default
  force-stop-build: true
---
version: 2
plan:
  key: VW-BROW
plan-permissions:
- users:
  - ubaid
  permissions:
  - view
  - edit
  - build
  - clone
  - admin
  - view-configuration
...
